### ISSUE TITLE
Remove all .js files in browser/base/content/newtab/ 

### ISSUE THREAD

**Issue by sarracini** [mozilla/newtab-dev#5]
Now that it's remotely hosted let's remove the .js files in the newtab folder since they're no longer being used. This includes:
cells.js, customize.js, drag.js, dragDataHelper.js, drop.js, dropPreview.js, dropTargetShim.js, grid.js, intro.js, page.js, search.js, sites.js, transfomations.js, undo.js, and updater.js

**Comment by marcoscaceres** [comment]
We will need to keep these around for a while, it seems.
